export const NATIONALITIES = [
  "Camerounais",
  "Camerounaise",
  "Français",
  "Française",
  "Nigérian",
  "Nigériane",
  "Centrafricain",
  "Centrafricaine",
  "Tchadien",
  "Tchadienne",
  "Congolais",
  "Congolaise",
  "Gabonais",
  "Gabonaise",
  "Sénégalais",
  "Sénégalaise",
  "Ivoirien",
  "Ivoirienne",
]

export const PROFESSIONS = [
  "Enseignante",
  "Enseignant",
  "Ménagère",
  "Commerçante",
  "Commerçant",
  "Médecin",
  "Ingénieur",
  "Technicien",
  "Technicienne",
  "Cultivateur",
  "Cultivatrice",
  "Éleveur",
  "Étudiante",
  "Étudiant",
  "Infirmier",
  "Infirmière",
  "Avocat",
  "Avocate",
  "Sans profession",
]
